// 规则模板预设
// 包含流媒体优化、游戏加速、办公直连等常用规则模板
// 使用占位符 {{PROXY}} 表示代理出口策略组

export const ruleTemplates = {
  streaming: {
    name: "流媒体优化",
    icon: "🎬",
    description: "Netflix、Disney+、YouTube 等流媒体服务走代理",
    rules: [
      "DOMAIN-SUFFIX,netflix.com,{{PROXY}}",
      "DOMAIN-SUFFIX,nflxvideo.net,{{PROXY}}",
      "DOMAIN-SUFFIX,nflxso.net,{{PROXY}}",
      "DOMAIN-SUFFIX,nflxext.com,{{PROXY}}",
      "DOMAIN-SUFFIX,disneyplus.com,{{PROXY}}",
      "DOMAIN-SUFFIX,disney-plus.net,{{PROXY}}",
      "DOMAIN-SUFFIX,dssott.com,{{PROXY}}",
      "DOMAIN-SUFFIX,bamgrid.com,{{PROXY}}",
      "DOMAIN-SUFFIX,youtube.com,{{PROXY}}",
      "DOMAIN-SUFFIX,googlevideo.com,{{PROXY}}",
      "DOMAIN-SUFFIX,ytimg.com,{{PROXY}}",
      "DOMAIN-SUFFIX,hbomax.com,{{PROXY}}",
      "DOMAIN-SUFFIX,hulu.com,{{PROXY}}",
      "DOMAIN-SUFFIX,huluim.com,{{PROXY}}",
      "DOMAIN-SUFFIX,primevideo.com,{{PROXY}}",
      "DOMAIN-SUFFIX,aiv-cdn.net,{{PROXY}}",
      "DOMAIN-SUFFIX,spotify.com,{{PROXY}}",
      "DOMAIN-SUFFIX,scdn.co,{{PROXY}}",
    ],
  },
  gaming: {
    name: "游戏加速",
    icon: "🎮",
    description: "Steam、Epic、PlayStation 等游戏平台走代理",
    rules: [
      "DOMAIN-SUFFIX,steampowered.com,{{PROXY}}",
      "DOMAIN-SUFFIX,steamcommunity.com,{{PROXY}}",
      "DOMAIN-SUFFIX,steamstatic.com,{{PROXY}}",
      "DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,{{PROXY}}",
      "DOMAIN-SUFFIX,epicgames.com,{{PROXY}}",
      "DOMAIN-SUFFIX,unrealengine.com,{{PROXY}}",
      "DOMAIN-SUFFIX,playstation.com,{{PROXY}}",
      "DOMAIN-SUFFIX,playstation.net,{{PROXY}}",
      "DOMAIN-SUFFIX,xbox.com,{{PROXY}}",
      "DOMAIN-SUFFIX,xboxlive.com,{{PROXY}}",
      "DOMAIN-SUFFIX,nintendo.com,{{PROXY}}",
      "DOMAIN-SUFFIX,nintendo.net,{{PROXY}}",
      "DOMAIN-SUFFIX,battle.net,{{PROXY}}",
      "DOMAIN-SUFFIX,blizzard.com,{{PROXY}}",
      "DOMAIN-SUFFIX,riotgames.com,{{PROXY}}",
      "DOMAIN-SUFFIX,leagueoflegends.com,{{PROXY}}",
      "DOMAIN-SUFFIX,ea.com,{{PROXY}}",
      "DOMAIN-SUFFIX,origin.com,{{PROXY}}",
    ],
  },
  office: {
    name: "办公直连",
    icon: "💼",
    description: "国内办公软件和常用网站走直连",
    rules: [
      "DOMAIN-SUFFIX,dingtalk.com,DIRECT",
      "DOMAIN-SUFFIX,alibaba.com,DIRECT",
      "DOMAIN-SUFFIX,aliyun.com,DIRECT",
      "DOMAIN-SUFFIX,taobao.com,DIRECT",
      "DOMAIN-SUFFIX,tmall.com,DIRECT",
      "DOMAIN-SUFFIX,qq.com,DIRECT",
      "DOMAIN-SUFFIX,weixin.qq.com,DIRECT",
      "DOMAIN-SUFFIX,wechat.com,DIRECT",
      "DOMAIN-SUFFIX,tenpay.com,DIRECT",
      "DOMAIN-SUFFIX,weibo.com,DIRECT",
      "DOMAIN-SUFFIX,weibo.cn,DIRECT",
      "DOMAIN-SUFFIX,baidu.com,DIRECT",
      "DOMAIN-SUFFIX,bdstatic.com,DIRECT",
      "DOMAIN-SUFFIX,feishu.cn,DIRECT",
      "DOMAIN-SUFFIX,feishu.net,DIRECT",
      "DOMAIN-SUFFIX,bytedance.com,DIRECT",
      "DOMAIN-SUFFIX,jd.com,DIRECT",
      "DOMAIN-SUFFIX,360.cn,DIRECT",
      "DOMAIN-SUFFIX,163.com,DIRECT",
      "DOMAIN-SUFFIX,126.com,DIRECT",
    ],
  },
  developer: {
    name: "开发者加速",
    icon: "💻",
    description: "GitHub、NPM、Docker 等开发资源走代理",
    rules: [
      "DOMAIN-SUFFIX,github.com,{{PROXY}}",
      "DOMAIN-SUFFIX,github.io,{{PROXY}}",
      "DOMAIN-SUFFIX,githubusercontent.com,{{PROXY}}",
      "DOMAIN-SUFFIX,githubassets.com,{{PROXY}}",
      "DOMAIN-SUFFIX,npmjs.com,{{PROXY}}",
      "DOMAIN-SUFFIX,npmjs.org,{{PROXY}}",
      "DOMAIN-SUFFIX,docker.com,{{PROXY}}",
      "DOMAIN-SUFFIX,docker.io,{{PROXY}}",
      "DOMAIN-SUFFIX,stackoverflow.com,{{PROXY}}",
      "DOMAIN-SUFFIX,stackexchange.com,{{PROXY}}",
      "DOMAIN-SUFFIX,medium.com,{{PROXY}}",
      "DOMAIN-SUFFIX,vercel.com,{{PROXY}}",
      "DOMAIN-SUFFIX,vercel.app,{{PROXY}}",
      "DOMAIN-SUFFIX,netlify.com,{{PROXY}}",
      "DOMAIN-SUFFIX,netlify.app,{{PROXY}}",
      "DOMAIN-SUFFIX,cloudflare.com,{{PROXY}}",
      "DOMAIN-SUFFIX,googlesource.com,{{PROXY}}",
    ],
  },
  social: {
    name: "社交媒体",
    icon: "📱",
    description: "Twitter、Instagram、Telegram 等社交平台走代理",
    rules: [
      "DOMAIN-SUFFIX,twitter.com,{{PROXY}}",
      "DOMAIN-SUFFIX,x.com,{{PROXY}}",
      "DOMAIN-SUFFIX,twimg.com,{{PROXY}}",
      "DOMAIN-SUFFIX,instagram.com,{{PROXY}}",
      "DOMAIN-SUFFIX,cdninstagram.com,{{PROXY}}",
      "DOMAIN-SUFFIX,facebook.com,{{PROXY}}",
      "DOMAIN-SUFFIX,fbcdn.net,{{PROXY}}",
      "DOMAIN-SUFFIX,telegram.org,{{PROXY}}",
      "DOMAIN-SUFFIX,t.me,{{PROXY}}",
      "DOMAIN-SUFFIX,reddit.com,{{PROXY}}",
      "DOMAIN-SUFFIX,redd.it,{{PROXY}}",
      "DOMAIN-SUFFIX,discord.com,{{PROXY}}",
      "DOMAIN-SUFFIX,discordapp.com,{{PROXY}}",
      "DOMAIN-SUFFIX,whatsapp.com,{{PROXY}}",
      "DOMAIN-SUFFIX,whatsapp.net,{{PROXY}}",
      "DOMAIN-SUFFIX,line.me,{{PROXY}}",
      "DOMAIN-SUFFIX,tiktok.com,{{PROXY}}",
    ],
  },
};

export default ruleTemplates;
