// 规则模板预设
// 包含流媒体优化、游戏加速、办公直连等常用规则模板

export const ruleTemplates = {
  streaming: {
    name: "流媒体优化",
    icon: "🎬",
    description: "Netflix、Disney+、YouTube 等流媒体服务走代理",
    rules: [
      "DOMAIN-SUFFIX,netflix.com,🌍 其他外网",
      "DOMAIN-SUFFIX,nflxvideo.net,🌍 其他外网",
      "DOMAIN-SUFFIX,nflxso.net,🌍 其他外网",
      "DOMAIN-SUFFIX,nflxext.com,🌍 其他外网",
      "DOMAIN-SUFFIX,disneyplus.com,🌍 其他外网",
      "DOMAIN-SUFFIX,disney-plus.net,🌍 其他外网",
      "DOMAIN-SUFFIX,dssott.com,🌍 其他外网",
      "DOMAIN-SUFFIX,bamgrid.com,🌍 其他外网",
      "DOMAIN-SUFFIX,youtube.com,🌍 其他外网",
      "DOMAIN-SUFFIX,googlevideo.com,🌍 其他外网",
      "DOMAIN-SUFFIX,ytimg.com,🌍 其他外网",
      "DOMAIN-SUFFIX,hbomax.com,🌍 其他外网",
      "DOMAIN-SUFFIX,hulu.com,🌍 其他外网",
      "DOMAIN-SUFFIX,huluim.com,🌍 其他外网",
      "DOMAIN-SUFFIX,primevideo.com,🌍 其他外网",
      "DOMAIN-SUFFIX,aiv-cdn.net,🌍 其他外网",
      "DOMAIN-SUFFIX,spotify.com,🌍 其他外网",
      "DOMAIN-SUFFIX,scdn.co,🌍 其他外网",
    ],
  },
  gaming: {
    name: "游戏加速",
    icon: "🎮",
    description: "Steam、Epic、PlayStation 等游戏平台走代理",
    rules: [
      "DOMAIN-SUFFIX,steampowered.com,🌍 其他外网",
      "DOMAIN-SUFFIX,steamcommunity.com,🌍 其他外网",
      "DOMAIN-SUFFIX,steamstatic.com,🌍 其他外网",
      "DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,🌍 其他外网",
      "DOMAIN-SUFFIX,epicgames.com,🌍 其他外网",
      "DOMAIN-SUFFIX,unrealengine.com,🌍 其他外网",
      "DOMAIN-SUFFIX,playstation.com,🌍 其他外网",
      "DOMAIN-SUFFIX,playstation.net,🌍 其他外网",
      "DOMAIN-SUFFIX,xbox.com,🌍 其他外网",
      "DOMAIN-SUFFIX,xboxlive.com,🌍 其他外网",
      "DOMAIN-SUFFIX,nintendo.com,🌍 其他外网",
      "DOMAIN-SUFFIX,nintendo.net,🌍 其他外网",
      "DOMAIN-SUFFIX,battle.net,🌍 其他外网",
      "DOMAIN-SUFFIX,blizzard.com,🌍 其他外网",
      "DOMAIN-SUFFIX,riotgames.com,🌍 其他外网",
      "DOMAIN-SUFFIX,leagueoflegends.com,🌍 其他外网",
      "DOMAIN-SUFFIX,ea.com,🌍 其他外网",
      "DOMAIN-SUFFIX,origin.com,🌍 其他外网",
    ],
  },
  office: {
    name: "办公直连",
    icon: "💼",
    description: "国内办公软件和常用网站走直连",
    rules: [
      "DOMAIN-SUFFIX,dingtalk.com,DIRECT",
      "DOMAIN-SUFFIX,alibaba.com,DIRECT",
      "DOMAIN-SUFFIX,aliyun.com,DIRECT",
      "DOMAIN-SUFFIX,taobao.com,DIRECT",
      "DOMAIN-SUFFIX,tmall.com,DIRECT",
      "DOMAIN-SUFFIX,qq.com,DIRECT",
      "DOMAIN-SUFFIX,weixin.qq.com,DIRECT",
      "DOMAIN-SUFFIX,wechat.com,DIRECT",
      "DOMAIN-SUFFIX,tenpay.com,DIRECT",
      "DOMAIN-SUFFIX,weibo.com,DIRECT",
      "DOMAIN-SUFFIX,weibo.cn,DIRECT",
      "DOMAIN-SUFFIX,baidu.com,DIRECT",
      "DOMAIN-SUFFIX,bdstatic.com,DIRECT",
      "DOMAIN-SUFFIX,feishu.cn,DIRECT",
      "DOMAIN-SUFFIX,feishu.net,DIRECT",
      "DOMAIN-SUFFIX,bytedance.com,DIRECT",
      "DOMAIN-SUFFIX,jd.com,DIRECT",
      "DOMAIN-SUFFIX,360.cn,DIRECT",
      "DOMAIN-SUFFIX,163.com,DIRECT",
      "DOMAIN-SUFFIX,126.com,DIRECT",
    ],
  },
  developer: {
    name: "开发者加速",
    icon: "💻",
    description: "GitHub、NPM、Docker 等开发资源走代理",
    rules: [
      "DOMAIN-SUFFIX,github.com,🌍 其他外网",
      "DOMAIN-SUFFIX,github.io,🌍 其他外网",
      "DOMAIN-SUFFIX,githubusercontent.com,🌍 其他外网",
      "DOMAIN-SUFFIX,githubassets.com,🌍 其他外网",
      "DOMAIN-SUFFIX,npmjs.com,🌍 其他外网",
      "DOMAIN-SUFFIX,npmjs.org,🌍 其他外网",
      "DOMAIN-SUFFIX,docker.com,🌍 其他外网",
      "DOMAIN-SUFFIX,docker.io,🌍 其他外网",
      "DOMAIN-SUFFIX,stackoverflow.com,🌍 其他外网",
      "DOMAIN-SUFFIX,stackexchange.com,🌍 其他外网",
      "DOMAIN-SUFFIX,medium.com,🌍 其他外网",
      "DOMAIN-SUFFIX,vercel.com,🌍 其他外网",
      "DOMAIN-SUFFIX,vercel.app,🌍 其他外网",
      "DOMAIN-SUFFIX,netlify.com,🌍 其他外网",
      "DOMAIN-SUFFIX,netlify.app,🌍 其他外网",
      "DOMAIN-SUFFIX,cloudflare.com,🌍 其他外网",
      "DOMAIN-SUFFIX,googlesource.com,🌍 其他外网",
    ],
  },
  social: {
    name: "社交媒体",
    icon: "📱",
    description: "Twitter、Instagram、Telegram 等社交平台走代理",
    rules: [
      "DOMAIN-SUFFIX,twitter.com,🌍 其他外网",
      "DOMAIN-SUFFIX,x.com,🌍 其他外网",
      "DOMAIN-SUFFIX,twimg.com,🌍 其他外网",
      "DOMAIN-SUFFIX,instagram.com,🌍 其他外网",
      "DOMAIN-SUFFIX,cdninstagram.com,🌍 其他外网",
      "DOMAIN-SUFFIX,facebook.com,🌍 其他外网",
      "DOMAIN-SUFFIX,fbcdn.net,🌍 其他外网",
      "DOMAIN-SUFFIX,telegram.org,🌍 其他外网",
      "DOMAIN-SUFFIX,t.me,🌍 其他外网",
      "DOMAIN-SUFFIX,reddit.com,🌍 其他外网",
      "DOMAIN-SUFFIX,redd.it,🌍 其他外网",
      "DOMAIN-SUFFIX,discord.com,🌍 其他外网",
      "DOMAIN-SUFFIX,discordapp.com,🌍 其他外网",
      "DOMAIN-SUFFIX,whatsapp.com,🌍 其他外网",
      "DOMAIN-SUFFIX,whatsapp.net,🌍 其他外网",
      "DOMAIN-SUFFIX,line.me,🌍 其他外网",
      "DOMAIN-SUFFIX,tiktok.com,🌍 其他外网",
    ],
  },
};

export default ruleTemplates;
